version: 2.1


jobs:
  run-katalon:
    docker:

      - image: katalonstudio/katalon:10.4.3
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio 10.4.3 Tests
          
          command: >-
            katalonc.sh 
            -projectPath="$(pwd)" 
            -apiKey="d1e929ac-be0f-4cec-a5fc-f9fd6d7c8485" 
            -retry=0 
            -testSuitePath="Test Suites/TS01" 
            -browserType="Chrome" 
            -executionProfile="default" 
            --config -webui.autoUpdateDrivers=true


workflows:
  build:
    jobs:
      - run-katalon
